#!/bin/sh

WAD_PATH=~/Library/Application\ Support/Zandronum
SKINS_PATH=$WAD_PATH/skins
BRUTAL_PATH=$WAD_PATH/brutal

echo "brutal_doom - Toggles Brutal Doom"
echo "... using a really ghetto hack"
echo
echo "Note: Don't run while Zandronum is running"
echo

if [ -d "$BRUTAL_PATH" ]; then
  echo "Brutal Doom is not enabled, trying to enable ..."
  mv -f "$BRUTAL_PATH" "$SKINS_PATH"

  if [ $? -eq 0 ]; then
    echo "Disabled sucessfully."
  else
    echo "Could not disable."
  fi
else
  echo "Brutal Doom is enabled, trying to disable ..."
  mv -f "$SKINS_PATH" "$BRUTAL_PATH"

  if [ $? -eq 0 ]; then
    echo "Enabled sucessfully."
  else
    echo "Could not enable."
  fi
fi
