#!/bin/sh

# stop-puma-dev -- stops puma-dev apps using USR1 signal

echo "Stopping puma-dev apps ..."

pkill -USR1 puma-dev

if [ "$?" = "0" ]; then
  echo "  puma-dev apps stopped :)"
else
  echo "  Danger Will Robinson!  Something went wrong!"
fi

echo

echo "Sopping fsevent_watch (cuasing: resources temporarily unavailable)"

pkill -HUP fsevent_watch

if [ "$?" = "0" ]; then
  echo "  fsevent_watch processes stopped :)"
else
  echo "  Oops.. something went wrong!"
fi

echo

